### ISSUE TITLE
Readme를 작성해주세요.

### ISSUE THREAD

**Issue by f-lab-kai** [f-lab-edu/thunder-market#1]
- 프로젝트 이름
- 프로젝트 가설
- 프로젝트 설명(워킹 스켈레톤 / MVP / 아이스박스)
- 프로젝트 아키텍처(생략 가능)
- 브랜치 전략 / 선택 이유
- 기술 환경(생략 가능)
- 화면(MVP)
- ERD(생략 가능)

**Comment by jjkim01** [comment]
2432728a4594fa28f177784cc547ac0e1ac7b186
위 커밋에서 작성했습니다.
